import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}

// for(let i=0;i<=primordial;i++){
//   if(i<=primordial/3 && isDivisible(i)){
//     l1.push(i)
//     count1++
//   }
//   else if(i==primordial/2 && isDivisible(i)){
//     l2.push(i)
//     l3.push(i)
//     count2++
//     count3++
//   }
//   else if(i>primordial/3 &&i<=primordial/2 && isDivisible(i)){
//     l2.push(i)
//     count2++
//   }
//   else if(i>primordial/2 && i<(primordial/3)*2 && isDivisible(i)){
//     l3.push(i)
//     count3++
//   }
//   else if(isDivisible(i)){
//     l4.push(i)
//     count4++
//   }
// }
